# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedSentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('shows_solidarity', models.BigIntegerField(blank=True, db_column='Shows_Solidarity', null=True)),
                ('shows_tension_release', models.BigIntegerField(blank=True, db_column='Shows_tension_release', null=True)),
                ('agrees', models.BigIntegerField(blank=True, db_column='Agrees', null=True)),
                ('gives_suggestion', models.BigIntegerField(blank=True, db_column='Gives_Suggestion', null=True)),
                ('gives_opinion', models.BigIntegerField(blank=True, db_column='Gives_opinion', null=True)),
                ('gives_orientation', models.BigIntegerField(blank=True, db_column='Gives_orientation', null=True)),
                ('asks_for_orientation', models.BigIntegerField(blank=True, db_column='Asks_for_orientation', null=True)),
                ('asks_for_opinon', models.BigIntegerField(blank=True, db_column='Asks_for_opinon', null=True)),
                ('asks_for_suggestion', models.BigIntegerField(blank=True, db_column='Asks_for_suggestion', null=True)),
                ('disagrees', models.BigIntegerField(blank=True, db_column='Disagrees', null=True)),
                ('shows_tension', models.BigIntegerField(blank=True, db_column='Shows_Tension', null=True)),
                ('shows_antagnism', models.BigIntegerField(blank=True, db_column='Shows_Antagnism', null=True)),
                ('thanks', models.BigIntegerField(blank=True, db_column='Thanks', null=True)),
                ('sorry', models.BigIntegerField(blank=True, db_column='Sorry', null=True)),
                ('calm', models.BigIntegerField(blank=True, db_column='Calm', null=True)),
                ('nervous', models.BigIntegerField(blank=True, db_column='Nervous', null=True)),
                ('careless', models.BigIntegerField(blank=True, db_column='Careless', null=True)),
                ('cautious', models.BigIntegerField(blank=True, db_column='Cautious', null=True)),
                ('agressive', models.BigIntegerField(blank=True, db_column='Agressive', null=True)),
                ('defensive', models.BigIntegerField(blank=True, db_column='Defensive', null=True)),
                ('happy', models.BigIntegerField(blank=True, db_column='Happy', null=True)),
                ('angry', models.BigIntegerField(blank=True, db_column='Angry', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('shows_solidarity', models.BigIntegerField(blank=True, db_column='Shows_Solidarity', null=True)),
                ('shows_tension_release', models.BigIntegerField(blank=True, db_column='Shows_tension_release', null=True)),
                ('agrees', models.BigIntegerField(blank=True, db_column='Agrees', null=True)),
                ('gives_suggestion', models.BigIntegerField(blank=True, db_column='Gives_Suggestion', null=True)),
                ('gives_opinion', models.BigIntegerField(blank=True, db_column='Gives_opinion', null=True)),
                ('gives_orientation', models.BigIntegerField(blank=True, db_column='Gives_orientation', null=True)),
                ('asks_for_orientation', models.BigIntegerField(blank=True, db_column='Asks_for_orientation', null=True)),
                ('asks_for_opinon', models.BigIntegerField(blank=True, db_column='Asks_for_opinon', null=True)),
                ('asks_for_suggestion', models.BigIntegerField(blank=True, db_column='Asks_for_suggestion', null=True)),
                ('disagrees', models.BigIntegerField(blank=True, db_column='Disagrees', null=True)),
                ('shows_tension', models.BigIntegerField(blank=True, db_column='Shows_Tension', null=True)),
                ('shows_antagnism', models.BigIntegerField(blank=True, db_column='Shows_Antagnism', null=True)),
                ('thanks', models.BigIntegerField(blank=True, db_column='Thanks', null=True)),
                ('sorry', models.BigIntegerField(blank=True, db_column='Sorry', null=True)),
                ('calm', models.BigIntegerField(blank=True, db_column='Calm', null=True)),
                ('nervous', models.BigIntegerField(blank=True, db_column='Nervous', null=True)),
                ('careless', models.BigIntegerField(blank=True, db_column='Careless', null=True)),
                ('cautious', models.BigIntegerField(blank=True, db_column='Cautious', null=True)),
                ('agressive', models.BigIntegerField(blank=True, db_column='Agressive', null=True)),
                ('defensive', models.BigIntegerField(blank=True, db_column='Defensive', null=True)),
                ('happy', models.BigIntegerField(blank=True, db_column='Happy', null=True)),
                ('angry', models.BigIntegerField(blank=True, db_column='Angry', null=True)),
            ],
            options={
                'db_table': 'sentiments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceToMark', models.IntegerField(default=2)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
