# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('try1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayTableOfMarkedComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Marked', models.TextField()),
                ('CommentId', models.IntegerField(default=0)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
