# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try1', '0004_auto_20170224_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayAll3Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OriginalComment', models.TextField()),
                ('marked1', models.TextField()),
                ('marked2', models.TextField()),
                ('marked3', models.TextField()),
            ],
        ),
    ]
